name: fmri_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - libstdcxx
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python==3.9.21
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - argparse
      - attrs
      - certifi
      - charset-normalizer
      - comet-ml
      - configobj
      - contourpy
      - cycler
      - datetime
      - dulwich
      - einops
      - everett
      - filelock
      - fonttools
      - fsspec
      - idna
      - importlib-resources
      - jinja2
      - joblib
      - jsonschema
      - jsonschema-specifications
      - kiwisolver
      - markdown-it-py
      - markupsafe
      - matplotlib
      - mdurl
      - monai==1.4.0
      - mpmath
      - munch
      - networkx
      - nibabel==5.3.2
      - numpy==1.26.4
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-cufile-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-cusparselt-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - packaging
      - pathlib2
      - pillow
      - psutil
      - pygments
      - pyparsing
      - python-box
      - python-dateutil
      - pytz
      - pyyaml
      - referencing
      - requests
      - requests-toolbelt
      - rich
      - rpds-py
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - semantic-version
      - sentry-sdk
      - simpleitk
      - simplejson
      - six
      - sympy
      - threadpoolctl
      - torch==2.7.0
      - tqdm
      - triton
      - typing-extensions
      - urllib3
      - wrapt
      - wurlitzer
      - zipp
      - zope-interface
