# Path to JSON file that holds all the dataset paths
json_path: 'data/json_datasets/functional_language_areas_mapping_fold_1.json'

# Project & experiment details
project_name: fmri
experiment_name: agynet_broca_fold1
experiment_number: _0
#########################################################################################
mri_dim: &mri_dim
    [160, 192, 160]

dtype: &dtype
    'float32'

gt: &gt
    'broca'

weights_path: "model_weights/experiments/agynet_broca_fold1/best_model.pt"
#########################################################################################

# Hyperparameters
batch_size: 1
shuffle_data: false
amp_dtype: torch.float32

# Dataset type 
dataset_type: Dataset

# Model Arguments
model_arguments:
    model_name: AGYnet
    out_channels: 2
    mri_dims: *mri_dim
    channels: [20, 40, 80, 160, 320]


# final activation
final_activation: false  # in AGYnet softmax is built in

# Metrics
metrics:
    DiceMetric:
        include_background: false
        get_not_nans: true
        ignore_empty: false
    Sensitivity:
        include_background: false
    Specificity:
        include_background: false
metricForSaving: DiceMetric


# MONAI transforms
defaultTransforms:
    LoadImaged:
        keys: ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        image_only: true
        ensure_channel_first: true
        dtype: *dtype
    ToTensord:
        keys: ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        dtype: *dtype
    JointCrop:
        keys: ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        significant_key: 'brain_mask'
    SpatialPadd:
        keys: ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        spatial_size: *mri_dim
    Normalize0to1:
        keys: ['t1']
    RenameKey:
        old_name: *gt # broca or wernicke keys
        new_name: "gt"
    AddBackgroundGTChannel:
        keys: ['gt']
    ConcatItemsd:
        keys: ["t1", "dec_rgb"]
        dim: 0
        name: "img"

transforms: {}
valTransforms: {}
testTransforms: {}


sets: ['test']
set2transforms:
    training: transforms
    validation: valTransforms
    test: testTransforms