# comet ML logging - Optional
log: False  # True/False
workspace: 'add your workspace here'
api_key: 'add your api key here'


# Path to JSON file that holds all the dataset paths
json_path: 'data/json_datasets/functional_language_areas_mapping_fold_0.json'

# Saves paths
save_weights_path: 'model_weights/experiments/'
save_checkpoints_path: 'model_checkpoints'

# Project & experiment details
project_name: fmri
experiment_name: swinunter_fold0
experiment_number: _0

#########################################################################################
dtype: &dtype
    'float32'
#########################################################################################

# Hyperparameters
anatomy_loss: True # True/False
batch_size: 1
epochs: 70
shuffle_data: true
amp_dtype: float32

# Use pretrained model from HCP
use_pretrained_hcp: True
pretrained_hcp_path: "model_weights/pre_trained_HCP/Swin-UNETR/pre_trained_swinunetr_brodmann_areas_hcp.pt"

# Dataset type 
dataset_type: Dataset

# Optimizer arguments
optimizer_arguments: 
    optimizer: 'Adam'

# Learning Rate Scheduler
scheduler_arguments: 
    scheduler: CyclicLR
    base_lr: 5e-5
    max_lr: 1e-4
    mode: triangular
    step_size_up: 15
    step_size_down: 15
    gamma: 0.5
    cycle_momentum: false

# Model Arguments
model_arguments:
    model_name: SwinUNETR
    img_size: [0, 0, 0] # this parameter is required but deprecated
    in_channels: 4
    out_channels: 3
    depths: [2, 2, 2, 2]
    num_heads: [1, 2, 3, 4]
    feature_size: 24
    drop_rate: 0.4
    attn_drop_rate: 0.4
    dropout_path_rate: 0.4

# Final activation 
final_activation: True

# Metrics
metrics:
    DiceMetric:
        include_background: false
        get_not_nans: true
        ignore_empty: false
metricForSaving: DiceMetric

# MONAI transforms
defaultTransforms:
    LoadImaged:
        keys: ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        image_only: true
        ensure_channel_first: true
        dtype: *dtype
    ToTensord:
        keys:  ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        dtype: *dtype
    JointCrop:
        keys:  ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        significant_key: 'brain_mask'
    DivisiblePadd:
        keys:  ['t1', 'dec_rgb', 'brain_mask', 'gm', 'broca', 'wernicke']
        k: 32
    Normalize0to1:
        keys: ['t1']
    ConcatItemsdClone:
        keys: ["broca", "wernicke"]
        dim: 0
        name: "gt"
    AddBackgroundGTChannel:
        keys: ['gt']
    ConcatItemsd:
        keys: ["t1", "dec_rgb"]
        dim: 0
        name: "img"

# MONAI transforms
transforms:
    RandomSagittalFlip:
        keys: ["img", "gt", "gm"]
    RandRotated:
        keys: ["img", "gt", "gm"]
        mode: ['bilinear', 'nearest', 'nearest']
        range_x: 0.1221 # 7 degrees
        range_y: 0.1221 # 7 degrees
        range_z: 0.1221 # 7 degrees

valTransforms: {}

# Utilities
sets: ['training', 'validation']
set2transforms:
    training: transforms
    validation: valTransforms
